### ISSUE TITLE
Request: Support PHPUnit 7 because... WordPress.

### ISSUE THREAD

**Issue by dac514** [krakjoe/pcov#25]
WordPress doesn't support PHPUnit 8, yet:

+ https://core.trac.wordpress.org/ticket/46149

Travis.CI started giving us out of memory errors. 

+ [First with xdebug in June 2016](http://kizu514.com/blog/phpdbg-is-much-faster-than-xdebug-for-code-coverage/)
+ [Today with phpdbg](https://github.com/pressbooks/pressbooks/issues/1745).
+ I'm stuck until I can try pcov

Did I mention WordPress.

Help? 😢

**Comment by rask** [comment]
This is mostly PHPUnit and php-code-coverage related, not PCOV, as they decide what coverage driver to load. PCOV support appeared in PHPUnit 8 as the php-code-coverage dependency introduced PCOV driver support in that release (php-code-coverage 7.x I think?).

The sanest approach would be to pester WordPress core developers to upgrade to PHPUnit 8, but I do understand that it would probably take ages to happen.

**Comment by michaelbutler** [comment]
Not sure why it is not mentioned in this project's README.md (maybe it should?) but there is a workaround for this... krakjoe created [pcov/clobber](https://github.com/krakjoe/pcov-clobber) as a small composer package that can be used to live patch PHPUnit 7 code to support pcov.

As a build prestep you could install clobber, run it on your project's root workspace, then run your test suite with pcov, then finally unclobber as a post step, and remove clobber package.

**Comment by rask** [comment]
@michaelbutler did not know about this, need to check it out. Thanks!

**Comment by krakjoe** [comment]
clobber is not mentioned in the readme because I would prefer if people just do the upgrade, clobber is not an elegant tool, it's a get-the-job-done tool that's fine to use temporarily, but I don't intend to maintain it into the future and it can't be considered a legitimate method of deploying pcov.

I totally get that it's not possible to "just do the upgrade", which is why clobber exists in the first place, but that we don't live in an ideal world is not a good excuse for failing to aim for ideal :)
