### ISSUE TITLE
Built-in server source discovery

### ISSUE THREAD

**Issue by SamMousa** [krakjoe/pcov#28]
In the codeception test suite the built-in server is used to test getting remote coverage.
While trying to switch over to pcov I discovered that pcov does not take into account the root directory passed into php via `-t`.

In my opinion it makes more sense to, in this case, default to the webroot than to the calling directory.
The 3 invocations below should result in the same coverage being shown.
```
> php -S 127.0.0.1:1234 -t /test/cool/stuff
> cd /test/cool php -S 127.0.0.1:1234 -t stuff
> cd /test/cool/stuff php -S 127.0.0.1:1234 -t .
```

Because of the auto discovery this is not the case.
To aid in debugging this, it might also make sense to somehow expose the discovered directory in use.

**Comment by krakjoe** [comment]
This has to be considered a configuration issue on the codeception side. The SAPI doesn't provide a standard way to get the docroot from any SAPI, and in the specific case of the cli-server, the struct that contains the document root is private and there is no way to access it.

I have added the detected directory to phpinfo() output, so that no longer displays the very unhelpful "auto".
