### ISSUE TITLE
Could you explain how PCOV calculates coverage

### ISSUE THREAD

**Issue by slavcodev** [krakjoe/pcov#44]
Hello.

We have a big discrepancies in code coverage using xDebug and PCOV in our project. For example there is 15% difference for covered lines.

There is a small part of README describes the difference, but I'm not 100% clear on that.

Рere on this example

![image](https://user-images.githubusercontent.com/757721/74781702-43915900-52a2-11ea-96a8-5be94ff422a2.png)

I'm confused that lines 90 and 91 are not covered according PCOV?

**Comment by krakjoe** [comment]
In general:

PCOV and Opcache share the same control flow graph, Xdebug builds it's own. 

PCOV will mark executed what is executable and actually executed at runtime (the VM is travelling opcodes on that specific line). 

Both Xdebug and PCOV have to make certain decisions about what to include in a report, Xdebug has to do so in light of its long history and PCOV has to do so in light of the future. Both seem to be making reasonable decisions.

In this specific case, pcov doesn't consider `ZEND_RECV` executable because `RECV` is an implementation detail of the VM, it may not always be traveled, furthermore, it may be on a line with interesting code, such as a function call.

Xdebug does consider it executable.
