### ISSUE TITLE
Closing braces not covered

### ISSUE THREAD

**Issue by SamMousa** [krakjoe/pcov#76]
![image](https://user-images.githubusercontent.com/547021/142010336-6d0b3e60-e517-41e6-ac2a-60953d07c9b7.png)

Mangling my code further does yield green coverage:

![image](https://user-images.githubusercontent.com/547021/142010580-05d1fd89-dac2-4968-96b7-2b00901e743f.png)

Let me know if any aditional information is required.

**Comment by xiak** [comment]
I have the same issue 

[root@3b737c8171f9 /]# yum list installed | grep pcov
php-pecl-pcov.x86_64                 1.0.11-1.el7.remi.7.4      @remi-php74 

php --version
PHP 7.2.34 (cli) (built: Nov 15 2021 09:20:49) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

phpunit --version
PHPUnit 8.5.9 by Sebastian Bergmann and contributors.

<img width="750" alt="coverage" src="https://user-images.githubusercontent.com/16730094/159851548-94830905-5004-4574-b8f6-20ead499a4fe.png">



**OK I have resolved this issue**

> If there are some blank lines at the end of the document, the issue will gone

**Comment by jrchamp** [comment]
Hi @SamMousa It seems like this issue is not resolved - at least it seems like I'm running into this issue today. Would you be willing to explain how/if you were able to resolve the issue? I'd prefer that this issue be reopened, but I do not have the power to do that myself without creating a new issue that would potentially duplicate/split the conversation. Thank you for your effort in reporting this issue.

**Comment by SamMousa** [comment]
Open a new one..
